export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const FETCH_POLLING_STATION_SUCCESS = 'FETCH_POLLING_STATION_SUCCESS';
export const FETCH_POLLING_STATION_ERROR = 'FETCH_POLLING_STATION_ERROR';
export const FETCH_POLLING_STATION_START = 'FETCH_POLLING_STATION_START';
export const FETCH_POLLING_STATION = 'FETCH_POLLING_STATION';

export const INSTALL_POLLING_STATION_SUCCESS = 'INSTALL_POLLING_STATION_SUCCESS';
export const INSTALL_POLLING_STATION_ERROR = 'INSTALL_POLLING_STATION_ERROR';
export const INSTALL_POLLING_STATION_START = 'INSTALL_POLLING_STATION_START';
export const INSTALL_POLLING_STATION = 'INSTALL_POLLING_STATION';