export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const BY_PASS_AUTH = 'BY_PASS_AUTH';
export const LOGOUT_ELECTOR = 'LOGOUT_ELECTOR';

export const FETCH_POLLING_STATION_SUCCESS = 'FETCH_POLLING_STATION_SUCCESS';
export const FETCH_POLLING_STATION_ERROR = 'FETCH_POLLING_STATION_ERROR';
export const FETCH_POLLING_STATION_START = 'FETCH_POLLING_STATION_START';
export const FETCH_POLLING_STATION = 'FETCH_POLLING_STATION';

export const INSTALL_POLLING_STATION_SUCCESS = 'INSTALL_POLLING_STATION_SUCCESS';
export const INSTALL_POLLING_STATION_ERROR = 'INSTALL_POLLING_STATION_ERROR';
export const INSTALL_POLLING_STATION_START = 'INSTALL_POLLING_STATION_START';
export const INSTALL_POLLING_STATION = 'INSTALL_POLLING_STATION';
export const BY_PASS_INSTALL = 'BY_PASS_INSTALL';

export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_ERROR = 'FETCH_CANDIDATES_ERROR';
export const FETCH_CANDIDATES_START = 'FETCH_CANDIDATES';
export const FETCH_CANDIDATES='FETCH_CANDIDATES';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS = 'FETCH_USERS';

export const SET_ELECTION_SELECTED = 'SET_ELECTIONS_SELECTED';

export const UPDATE_LOCAL_USER = 'UPDATE_LOCAL_USER'